# Generated by Django 5.0.6 on 2024-06-19 22:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garden_app", "0002_rename_uploaded_at_upload_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gardeninggroup",
            name="garden",
        ),
        migrations.AddField(
            model_name="gardeninggroup",
            name="description",
            field=models.TextField(default="No Description"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gardeninggroup",
            name="image",
            field=models.ImageField(default="No", upload_to="group_images/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="gardeninggroup",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="gardening_groups", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="gardeninggroup",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
