# Generated by Django 5.0.6 on 2024-07-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garden_app", "0005_rename_grouppost_post_alter_post_options_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
